### ISSUE TITLE
.call method does not support the "verify" argument.

### ISSUE THREAD

**Issue by xtakacsx** [kiwicom/schemathesis#277]
response = case.call(BASE_URL, verify=False, timeout=1000)

does not take into consideration the verify=False argument.

**Comment by Stranger6667** [comment]
Hello @xtakacsx !

Thank you for the report, I will take a look

**Comment by Stranger6667** [comment]
Could you, please, provide some more context about your use case? I can't reproduce it

The `kwargs` in `case.call` are passed to `requests.Session.request`  without modifications, when I run:

```
case.call("http://127.0.0.1:8081/", verify=False, timeout=1000)
```

then the underlying `send_kwargs` from [here](https://github.com/psf/requests/blob/master/requests/sessions.py#L530) contains the proper value:

```
{'timeout': 1000, 'allow_redirects': True, 'verify': False, 'proxies': OrderedDict(), 'stream': False, 'cert': None}
```

All next steps are related to the `requests` behavior

**Comment by xtakacsx** [comment]
Hello @Stranger6667,

Sorry for the late reply.
I used this code with version 0.10 before updating to 0.15, it stopped working:
`import schemathesis
from hypothesis import settings
import urllib3
urllib3.disable_warnings()

BASE_URL = "https://<some_url_address>"
schema = schemathesis.from_uri(f"{BASE_URL}/swagger/docs/V1")

@schema.parametrize()
@settings(deadline=None)
def test_no_server_errors(case):
    response = case.call(BASE_URL, verify=False, timeout=1000)
    assert response.status_code < 500`

As a workaround: i had to update the cacert.pem found in the site-packages\certifi folder

**Comment by Stranger6667** [comment]
Does this test work if you re-install schemathesis 0.10? Also what is the exact error that happens during the `call` execution?

**Comment by xtakacsx** [comment]
I does not work with 0.10:
```
____________________________________________________________________________________________________ ERROR collecting test_api.py ____________________________________________________________________________________________________
venv2\lib\site-packages\schemathesis\extra\pytest_plugin.py:51: in collect
    item for endpoint in self.schemathesis_case.get_all_endpoints() for item in self._gen_items(endpoint)
venv2\lib\site-packages\schemathesis\extra\pytest_plugin.py:51: in <listcomp>
    item for endpoint in self.schemathesis_case.get_all_endpoints() for item in self._gen_items(endpoint)
venv2\lib\site-packages\schemathesis\extra\pytest_plugin.py:39: in _gen_items
    hypothesis_item = create_test(endpoint, self.test_function)
venv2\lib\site-packages\schemathesis\_hypothesis.py:20: in create_test
    original_test = get_original_test(test)
venv2\lib\site-packages\schemathesis\_hypothesis.py:32: in get_original_test
    return test._hypothesis_internal_test_function_without_warning  # type: ignore
E   AttributeError: 'function' object has no attribute '_hypothesis_internal_test_function_without_warning'

During handling of the above exception, another exception occurred:
venv2\lib\site-packages\schemathesis\extra\pytest_plugin.py:54: in collect
    pytest.fail("Error during collection")
E   Failed: Error during collection
```
And i get this error with 0.15:

```
____________________________________________________________________________________________________ ERROR collecting test_api.py ____________________________________________________________________________________________________
venv2\lib\site-packages\urllib3\connectionpool.py:672: in urlopen
    chunked=chunked,
venv2\lib\site-packages\urllib3\connectionpool.py:376: in _make_request
    self._validate_conn(conn)
venv2\lib\site-packages\urllib3\connectionpool.py:994: in _validate_conn
    conn.connect()
venv2\lib\site-packages\urllib3\connection.py:394: in connect
    ssl_context=context,
venv2\lib\site-packages\urllib3\util\ssl_.py:370: in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
..\..\AppData\Local\Programs\Python\Python37-32\lib\ssl.py:423: in wrap_socket
    session=session
..\..\AppData\Local\Programs\Python\Python37-32\lib\ssl.py:870: in _create
    self.do_handshake()
..\..\AppData\Local\Programs\Python\Python37-32\lib\ssl.py:1139: in do_handshake
    self._sslobj.do_handshake()
E   ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)

During handling of the above exception, another exception occurred:
venv2\lib\site-packages\requests\adapters.py:449: in send
    timeout=timeout
venv2\lib\site-packages\urllib3\connectionpool.py:720: in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
venv2\lib\site-packages\urllib3\util\retry.py:436: in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
E   urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='test-maps-catalog.ubisoft.org', port=443): Max retries exceeded with url: /swagger/docs/V1 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FA
ILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)')))

During handling of the above exception, another exception occurred:
test_api.py:10: in <module>
    schema = schemathesis.from_uri(f"{BASE_URL}/swagger/docs/V1")
venv2\lib\site-packages\schemathesis\loaders.py:36: in from_uri
    response = session.get(uri)
venv2\lib\site-packages\requests\sessions.py:546: in get
    return self.request('GET', url, **kwargs)
venv2\lib\site-packages\requests\sessions.py:533: in request
    resp = self.send(prep, **send_kwargs)
venv2\lib\site-packages\requests\sessions.py:646: in send
    r = adapter.send(request, **kwargs)
venv2\lib\site-packages\requests\adapters.py:514: in send
    raise SSLError(e, request=request)
E   requests.exceptions.SSLError: HTTPSConnectionPool(host='test-maps-catalog.ubisoft.org', port=443): Max retries exceeded with url: /swagger/docs/V1 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED
] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)')))

```

**Comment by Stranger6667** [comment]
hm, as for the first error - it is caused by the new hypothesis version, schemathesis 0.10.0 supports Hypothesis < 4.42.4. It should work if you'll install e.g. `hypothesis==4.42.3`.

As for the second one - we used `urllib` in `loaders` and it didn't complain about certs probably for this reason. In the recent versions, we switched to `requests`., and that call doesn't receive any kwargs. 

I will investigate in more details why this behavior differs between `urllib` & `requests` and will fix it. At least will make it possible to pass custom kwargs to `from_uri` so you could use `verify=False`

**Comment by Stranger6667** [comment]
Thank you once again for reporting this

**Comment by Stranger6667** [comment]
I'll try to issue a new release with this fix tomorrow

**Comment by xtakacsx** [comment]
> 
> 
> Thank you once again for reporting this

No problem, 
Thank you for maintaining this lib

**Comment by Stranger6667** [comment]
Btw, what version of `certifi` do you have? and if it is not the most recent one, does upgrading to the most recent one help?

**Comment by Stranger6667** [comment]
Unfortunately, it is hard to reproduce the issue for me, here is the old version of `from_uri` loader, could you check if it works, please? 

```
from schemathesis.utils import get_base_url
from schemathesis import from_file
from urllib.request import urlopen

def from_uri(uri, base_url=None, method=None, endpoint=None):
    response = urlopen(uri)
    data = response.read()
    if base_url is None:
        base_url = get_base_url(uri)
    return from_file(data, base_url=base_url, method=method, endpoint=endpoint)
```

So we can exclude that the issue depends on some another package

**Comment by xtakacsx** [comment]
I use `certifi ` 2019.9.11 (latest version). 
As for the from_uri test: schemathesis.from_uri() does not work, using the old from_uri() works!

**Comment by Stranger6667** [comment]
Hm ... it is strange, we've released a new version - 0.16.0, now it should be possible to pass `verify=False` to `from_uri` call - hope it can work as a workaround for now.

Personally I faced a similar problem on my Mac machine - and it was solved by running `Install Certificates.command` which is bundled with the default Python downloadable package for Mac OS X. Not sure if there is something similar for Windows (I assume it from the command line output)

**Comment by xtakacsx** [comment]
I know that this is off topic but can you provide some examples for:
- Any call will be processed in <50 ms - you can verify the app performance;
- Any unauthorized access will end with 401 HTTP response code;

for example `assert response.elapsed.total_seconds() < 1` passes the test

**Comment by Stranger6667** [comment]
The issue itself is resolved - `from_uri` supports `verify` argument. Feel free to reopen the issue in case if the problem will occur again
